"""
Sphinx Documentation Compiler Script
"""
import os
import subprocess
import sys

def main():
    print("═══════════════════════════════════════════════════════════════════════")
    print("                   FinParse API Sphinx Docs Compiler                   ")
    print("═══════════════════════════════════════════════════════════════════════")

    # 1. Check/Install dependencies
    print("Checking Sphinx, Furo theme, myst-parser, and mermaid dependencies...")
    try:
        import sphinx
        import furo
        import myst_parser
        import sphinxcontrib.mermaid
    except ImportError:
        print("Missing Sphinx dependencies. Installing via pip...")
        subprocess.check_call([
            sys.executable, "-m", "pip", 
            "install", "sphinx", "furo", "myst-parser", "sphinxcontrib-mermaid"
        ])

    docs_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(docs_dir, "../../"))
    output_dir = os.path.join(docs_dir, "build")

    # 2. Cleanup old autogenerated RST blueprints
    print("\nCleaning up previous autogenerated module blueprints...")
    for file in os.listdir(docs_dir):
        if (file.startswith("app") or file == "modules.rst") and file.endswith(".rst"):
            try:
                os.remove(os.path.join(docs_dir, file))
            except Exception as e:
                print(f"  Warning: could not delete {file}: {e}")

    # 3. Generate RST Blueprints using sphinx-apidoc
    print("\nRunning sphinx-apidoc to automatically map codebase packages in app/...")
    try:
        subprocess.check_call([
            sys.executable, "-m", "sphinx.ext.apidoc",
            "-o", docs_dir,
            os.path.join(project_root, "app"),
            "-f",
            "--separate",
            "--no-toc"
        ])
        print("  RST blueprint files generated successfully.")
    except Exception as e:
        print(f"❌ Error running sphinx-apidoc: {e}")
        sys.exit(1)

    # 4. Generate custom modules.rst if missing
    modules_rst_path = os.path.join(docs_dir, "modules.rst")
    if not os.path.exists(modules_rst_path):
        print("Generating modules.rst...")
        # Create standard modules table of contents
        with open(modules_rst_path, "w") as f:
            f.write("Code Reference\n")
            f.write("==============\n\n")
            f.write(".. toctree::\n")
            f.write("   :maxdepth: 4\n\n")
            # List all app.* packages generated by apidoc
            app_docs = [file[:-4] for file in os.listdir(docs_dir) if file.startswith("app") and file.endswith(".rst")]
            for doc in sorted(app_docs):
                f.write(f"   {doc}\n")

    # 5. Build HTML Documentation
    print("\nCompiling HTML pages using sphinx-build...")
    try:
        subprocess.check_call([
            sys.executable, "-m", "sphinx.cmd.build",
            "-b", "html",
            docs_dir,
            output_dir
        ])
        print("\n🎉 Documentation built successfully!")
        print(f"Open this URL in your web browser to view:")
        print(f"file:///{os.path.join(output_dir, 'index.html').replace(os.sep, '/')}")
    except Exception as e:
        print(f"❌ Error compiling documentation: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
