"""initial_schema

Revision ID: 6b0377b77fbb
Revises: 
Create Date: 2026-05-29 20:19:59.992757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.custom_types


# revision identifiers, used by Alembic.
revision: str = '6b0377b77fbb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('document_type', sa.Enum('INVOICE', 'BANK_STATEMENT', name='document_type_enum'), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(is_deleted = FALSE AND deleted_at IS NULL) OR (is_deleted = TRUE AND deleted_at IS NOT NULL)', name='chk_documents_deleted_at_consistency'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum_sha256')
    )
    op.create_table('vendors',
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('raw_names', app.models.custom_types.TextArray(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name', name='uq_vendor_canonical_name')
    )
    op.create_table('document_tags',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'key', name='uq_document_tag')
    )
    op.create_table('processing_jobs',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL', name='job_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_detail', sa.JSON(), nullable=True, comment='Structured: {stage, field, raw_value, traceback}'),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('max_retries', sa.SmallInteger(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=True, comment='Array: [{field, message}] — non-fatal issues during parsing'),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('is_reprocess', sa.Boolean(), nullable=False, comment='TRUE when triggered by allow_reprocess=true'),
    sa.Column('pdf_password_used', sa.Boolean(), nullable=False),
    sa.Column('pdf_encryption_type', sa.String(length=50), nullable=True),
    sa.Column('ocr_used', sa.Boolean(), nullable=False),
    sa.Column('ocr_engine', sa.String(length=50), nullable=True),
    sa.Column('ocr_confidence_avg', sa.Float(), nullable=True),
    sa.Column('scanned_pages', app.models.custom_types.IntegerArray(), nullable=True, comment='Page numbers (1-indexed) that required OCR'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_statements',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('processing_job_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=True, comment='MASKED — last 4 digits only. e.g. ****4321'),
    sa.Column('account_holder', sa.String(length=500), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('statement_from', sa.Date(), nullable=True),
    sa.Column('statement_to', sa.Date(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('closing_balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('raw_headers', sa.JSON(), nullable=True, comment='Original CSV column names as-is, for debugging format mismatches'),
    sa.Column('detected_format', sa.String(length=100), nullable=True, comment='Detected bank format: HDFC_V2, ICICI_STANDARD, GENERIC, etc.'),
    sa.Column('detected_delimiter', sa.String(length=1), nullable=True),
    sa.Column('detected_encoding', sa.String(length=30), nullable=True),
    sa.Column('total_rows_parsed', sa.Integer(), nullable=True),
    sa.Column('total_rows_skipped', sa.Integer(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('processing_job_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=255), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('raw_vendor_name', sa.String(length=500), nullable=True),
    sa.Column('raw_date_text', sa.String(length=100), nullable=True),
    sa.Column('raw_total_text', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('page_range_start', sa.SmallInteger(), nullable=True),
    sa.Column('page_range_end', sa.SmallInteger(), nullable=True),
    sa.Column('invoice_index', sa.SmallInteger(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='chk_invoice_confidence_range'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_transactions',
    sa.Column('bank_statement_id', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=True, comment='Original CSV text before cleaning'),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('transaction_type', sa.Enum('CREDIT', 'DEBIT', 'TRANSFER', 'FEE', 'INTEREST', 'UNKNOWN', name='transaction_type_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='Always positive. Use direction column for sign.'),
    sa.Column('direction', sa.String(length=1), nullable=False, comment='C = Credit (money in), D = Debit (money out)'),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True, comment='Per-row currency for multi-currency statements'),
    sa.Column('row_index', sa.Integer(), nullable=False, comment='Original CSV row number (1-indexed) for debugging'),
    sa.Column('parse_warnings', sa.JSON(), nullable=True, comment="Row-level warnings: ['date guessed', 'amount format unusual']"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("direction IN ('C', 'D')", name='chk_bank_tx_direction'),
    sa.CheckConstraint('amount >= 0', name='chk_bank_tx_amount_positive'),
    sa.ForeignKeyConstraint(['bank_statement_id'], ['bank_statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_line_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'line_number', name='uq_invoice_line_item_order')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_line_items')
    op.drop_table('bank_transactions')
    op.drop_table('invoices')
    op.drop_table('bank_statements')
    op.drop_table('processing_jobs')
    op.drop_table('document_tags')
    op.drop_table('vendors')
    op.drop_table('documents')
    # ### end Alembic commands ###
